### ISSUE TITLE
When I run python3 summarize.py

### ISSUE THREAD

**Issue by Youngest23** [pfandzelter/optimal-leo-placement#3]
When I run python3 summarize.py 
The error is "No such file or directory: '/optimal-leo-placement/placement-distances/st1-0.csv'"
what code should i run to generate the csv file?

**Comment by pfandzelter** [comment]
Please follow the steps in the README:
1. `python3 shells.py`
2. `python3 distances.py`
3. then `python3 summarize.py`

**Comment by Youngest23** [comment]
I followed the steps in the README. 
In summarize.py line 21,  "results_file = os.path.join(config.PLACEMENT_DISTANCES_DIR, "{}-{}.csv".format(name, next_step))"
It needs {}-{}.csv , it didn't generate before in shells.py or distances.py

**Comment by Wonderful23** [comment]
I also have this problem

**Comment by pfandzelter** [comment]
Now I see what the issue was, I accidentally deleted `placement-distances.py` in an old commit. I have no restored it and updated the README again. Please see if you can run everything now with the new instructions in the README

**Comment by Wonderful23** [comment]
Thank you for your commit,but there is a problem.  "PLACEMENT_DISTANCES_DIR" appears three times,so in summarize.py line 21, "results_file = os.path.join(config.PLACEMENT_DISTANCES_DIR, "{}-{}.csv".format(name, next_step))"

**Comment by pfandzelter** [comment]
I see, I've updated the output directory of `placement-distances.py`

**Comment by Youngest23** [comment]
What is meaning of the vertical line and horizontal line in the graphs?  
![graph](https://user-images.githubusercontent.com/90636009/228527051-1a9c64f8-a4b4-4380-be14-082c52013dbd.png)
![image](https://user-images.githubusercontent.com/90636009/228527568-abb9f5be-77b8-47bc-9d7e-17a7d5fbfc37.png)

**Comment by pfandzelter** [comment]
That's a box plot, you can read more about the components here: https://chartio.com/learn/charts/box-plot-complete-guide/

**Comment by EipNit** [comment]
df["SLO"] = df["type"].astype(str) + "-" + df["d"].astype(str)
KeyError: 'd'
